### ISSUE TITLE
Использовать инициализацию для всех переменных

### ISSUE THREAD

**Issue by dvpsun** [devourers/absolute-moment-computation#1]
- инициализируйте **все** переменные
- используйте default member initializer (https://en.cppreference.com/w/cpp/language/data_members)
```
truct Node {
	int key = 0;
	int left = 0;
	int right = 0;
...
```

**Comment by devourers** [comment]
исправлено в https://github.com/devourers/absolute-moment-computation/commit/e0afbab77294d41be5b19b133762558d36964260

**Comment by dvpsun** [comment]
Не исправленно. В коде осталось много мест, где стоит прописать инициализацию.
