### ISSUE TITLE
Написать комментарии

### ISSUE THREAD

**Issue by dvpsun** [devourers/absolute-moment-computation#3]
Написать комментарии в коде.

**Comment by devourers** [comment]
испрвлено в https://github.com/devourers/absolute-moment-computation/commit/e0afbab77294d41be5b19b133762558d36964260

**Comment by dvpsun** [comment]
Напишите комментарий:
- к каждому члену всех структур данных
- к каждому параметру функции
В качестве формата воспользуйтесь DoxyGen.
